/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.unto.twitter;

import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.io.IOException;

import javax.swing.JLabel;

import org.apache.commons.io.IOUtils;
import org.apache.http.HttpResponse;
import org.apache.http.client.ClientProtocolException;
import org.apache.http.client.HttpClient;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.client.DefaultHttpClient;
import org.json.JSONArray;
import org.json.JSONObject;

//Ruby 

import oauth.signpost.OAuthConsumer;
import oauth.signpost.commonshttp.CommonsHttpOAuthConsumer;
import oauth.signpost.exception.OAuthCommunicationException;
import oauth.signpost.exception.OAuthExpectationFailedException;
import oauth.signpost.exception.OAuthMessageSignerException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mattfishman
 */
public class Tweet extends javax.swing.JFrame {
    
    private String tweet;
    static String consumerKeyStr = "U3ExCXgiOZJLkkmKVecO64nis";
    static String consumerSecretStr = "vt838sU3QiG8Fb7w7xOFCWegWaVGLfd8an763EtVUUoGPfBdMl";
    static String accessTokenStr = "";
    static String accessTokenSecretStr = "";

    /**
     * Creates new form Tweet
     */
    public Tweet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        FollowingNum = new javax.swing.JLabel();
        MostRecent = new javax.swing.JLabel();
        FollowersNum = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        confirmButton = new javax.swing.JButton();
        Name = new javax.swing.JLabel();
        Description = new javax.swing.JLabel();
        Location = new javax.swing.JLabel();
        FavoritesNum = new javax.swing.JLabel();
        Followers = new javax.swing.JLabel();
        Following = new javax.swing.JLabel();
        Tweets = new javax.swing.JLabel();
        TweetsNum = new javax.swing.JLabel();
        Favorites = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        FollowingNum.setText("jLabel1");

        MostRecent.setText("Most Recent Tweet: ");

        FollowersNum.setText("jLabel1");

        usernameField.setText("Enter Username");
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            }
        });

        confirmButton.setText("Submit");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        Name.setText("jLabel1");

        Description.setText("jLabel1");

        Location.setText("jLabel2");

        FavoritesNum.setText("jLabel1");

        Followers.setText("Followers:");

        Following.setText("Following:");

        Tweets.setText("Tweets:");

        TweetsNum.setText("jLabel1");

        Favorites.setText("Favorites:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setDragEnabled(false);
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Following)
                    .addComponent(FollowingNum))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Followers)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(FollowersNum)))
                .addGap(91, 91, 91)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(FavoritesNum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TweetsNum))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Favorites)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(Tweets)))
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Name)
                    .addComponent(Description)
                    .addComponent(Location))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(confirmButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(MostRecent)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Description)
                .addGap(4, 4, 4)
                .addComponent(Location)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Followers)
                    .addComponent(Favorites)
                    .addComponent(Tweets)
                    .addComponent(Following))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FollowingNum)
                    .addComponent(FollowersNum)
                    .addComponent(FavoritesNum)
                    .addComponent(TweetsNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(MostRecent, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmButton)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        usernameField.addFocusListener(new FocusListener() {
          public void focusLost(FocusEvent arg0) {
          }
          public void focusGained(FocusEvent arg0) {
              if(usernameField.getText().matches("Enter Username"))
                usernameField.setText("");
          }
      });
    }// </editor-fold>                                                                  

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
      OAuthConsumer oAuthConsumer = new CommonsHttpOAuthConsumer(consumerKeyStr,consumerSecretStr);
      oAuthConsumer.setTokenWithSecret(accessTokenStr, accessTokenSecretStr);
      String username = usernameField.getText();
      HttpGet httpget =  new HttpGet("https://api.twitter.com/1.1/users/show.json?screen_name=" + username);
   


      HttpClient httpClient = new DefaultHttpClient();

      try {
        oAuthConsumer.sign(httpget);

        HttpResponse httpResponse;


        httpResponse = httpClient.execute(httpget);

        int statusCode = httpResponse.getStatusLine().getStatusCode();
//        System.out.println(
//            statusCode + ':' + httpResponse.getStatusLine().getReasonPhrase());
//        System.out
//            .println(IOUtils.toString(httpResponse.getEntity().getContent()));
//       
       String userProfile = IOUtils.toString(httpResponse.getEntity().getContent());
       //System.out.println(userProfile);
       StringBuilder sb = new StringBuilder(userProfile);
       sb.insert(sb.length(),"]");
       sb.insert(0,"[");
       userProfile = sb.toString();
       
       JSONArray json = new JSONArray(userProfile);
       
       JSONArray userProfiles = new JSONArray(userProfile);
       String accountName = null;
       String accountDescription = null;
       String accountLocation = null;
       int accountFollowers = 0;
       int accountFollowing = 0;
       int accountFavorites = 0;
       int accountTweets = 0;
       JSONObject status = null;
       String recentTweet = null;
       for(int i=0;i<json.length();i++){                        
         JSONObject u = userProfiles.getJSONObject(i);
         accountName = u.getString("name");
         accountDescription = u.getString("description");
         accountLocation = u.getString("location");
         accountFollowers = u.getInt("followers_count");
         accountFollowing = u.getInt("friends_count");
         accountFavorites = u.getInt("favourites_count");
         accountTweets = u.getInt("statuses_count");
         status = u.getJSONObject("status");
       }
       String statusString = status.toString();
       StringBuilder sb2 = new StringBuilder(statusString);
       sb2.insert(sb2.length(),"]");
       sb2.insert(0,"[");
       statusString = sb2.toString();
       JSONArray tweet = new JSONArray(statusString);
       for(int i=0;i<json.length();i++){
         JSONObject u = tweet.getJSONObject(i);
         recentTweet = u.getString("text");
       }
     
       //System.out.println(accountName);
       Name.setText(accountName);
       Description.setText(accountDescription);
       Location.setText(accountLocation);
       FollowersNum.setText(Integer.toString(accountFollowers));
       FollowingNum.setText(Integer.toString(accountFollowing));
       FavoritesNum.setText(Integer.toString(accountFavorites));
       TweetsNum.setText(Integer.toString(accountTweets));
       jTextArea1.setText(recentTweet);
       
       

      } catch (ClientProtocolException e) {
        System.out.println("Authentication failed Client Protocol Exception");
        // TODO Auto-generated catch block
        e.printStackTrace();
      } catch (IOException e) {
        // TODO Auto-generated catch block
        System.out.println("Just IO");
        e.printStackTrace();
      } catch (OAuthMessageSignerException e) {
        System.out.println("Authentication failed Signer");
        // TODO Auto-generated catch block
        System.out.println("Authentication failed");
        e.printStackTrace();
      } catch (OAuthExpectationFailedException e) {
        System.out.println("Authentication failed");
        // TODO Auto-generated catch block
        e.printStackTrace();
      } catch (OAuthCommunicationException e) {
        System.out.println("Authentication failed Communication");
        // TODO Auto-generated catch block
        e.printStackTrace(); 
        
      }

    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tweet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tweet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tweet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tweet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tweet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Description;
    private javax.swing.JLabel Favorites;
    private javax.swing.JLabel FavoritesNum;
    private javax.swing.JLabel Followers;
    private javax.swing.JLabel FollowersNum;
    private javax.swing.JLabel Following;
    private javax.swing.JLabel FollowingNum;
    private javax.swing.JLabel Location;
    private javax.swing.JLabel MostRecent;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Tweets;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel TweetsNum;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField usernameField;
    // End of variables declaration                   
}
